import { test, expect } from '@playwright/test';

// These are the five production pages that must always be available.
const primaryPages = [
  { name: 'home', path: '/', status: 200 },
  { name: 'products', path: '/products/', status: 200 },
  { name: 'faq', path: '/faq/', status: 200 },
  { name: 'about', path: '/about/', status: 200 },
  { name: 'contacts', path: '/contacts/', status: 200 },
];

// This deliberately nonexistent address verifies the real IIS 404 path.
const errorPage = {
  name: '404',
  path: '/__bts_release_smoke_missing_page__',
  status: 404,
};

// These paths are generated by the common navigation code in assets/main.js.
const navigationPaths = [
  '/',
  '/products/',
  '/contacts/',
  '/faq/',
  '/about/',
];

// Only resources capable of breaking the visible site are treated as critical here.
// Fonts and optional background requests are intentionally not release blockers.
const criticalResourceTypes = new Set([
  'stylesheet',
  'script',
  'image',
]);

// Return true only for requests that belong to the BTS staging origin.
// This prevents an unrelated external request from becoming a false release failure.
function isStageRequest(url) {
  try {
    return new URL(url).origin === 'https://stage.btsys.ru';
  } catch {
    return false;
  }
}

// Attach lightweight runtime diagnostics before navigation begins.
function watchPage(page) {
  // Store uncaught JavaScript exceptions.
  const pageErrors = [];

  // Store failed network requests for critical static resources.
  const failedRequests = [];

  // Store HTTP error responses for critical static resources.
  const badResponses = [];

  // An uncaught page exception is considered a critical JavaScript failure.
  page.on('pageerror', error => {
    pageErrors.push(error.message);
  });

  // A network-level failure means the browser could not obtain the resource at all.
  page.on('requestfailed', request => {
    if (
      criticalResourceTypes.has(request.resourceType()) &&
      isStageRequest(request.url())
    ) {
      failedRequests.push(
        `${request.resourceType()} ${request.url()} :: ` +
        `${request.failure()?.errorText || 'request failed'}`
      );
    }
  });

  // HTTP 4xx/5xx responses for CSS, JS or images are also release failures.
  page.on('response', response => {
    const request = response.request();

    if (
      criticalResourceTypes.has(request.resourceType()) &&
      isStageRequest(response.url()) &&
      response.status() >= 400
    ) {
      badResponses.push(
        `${response.status()} ${request.resourceType()} ${response.url()}`
      );
    }
  });

  return {
    pageErrors,
    failedRequests,
    badResponses,
  };
}

// Check whether currently visible images have actually decoded to nonzero dimensions.
async function findBrokenVisibleImages(page) {
  // Collect all image elements present on the current page.
  const images = page.locator('img');

  // Read the number once so DOM traversal remains deterministic.
  const count = await images.count();

  // Store only images that fail to load or decode.
  const brokenImages = [];

  // Check every image independently.
  for (let index = 0; index < count; index += 1) {
    // Select one concrete image element.
    const image = images.nth(index);

    // Move the image into the viewport.
    // This intentionally triggers native loading="lazy" behaviour.
    await image.scrollIntoViewIfNeeded();

    try {
      // Wait until the browser reports that the image has finished loading
      // and decoded to a real nonzero intrinsic width.
      await image.evaluate(element => {
        if (element.complete && element.naturalWidth > 0) {
          return;
        }

        return new Promise((resolve, reject) => {
          const timer = setTimeout(() => {
            reject(new Error('image load timeout'));
          }, 5000);

          element.addEventListener('load', () => {
            clearTimeout(timer);

            if (element.naturalWidth > 0) {
              resolve();
            } else {
              reject(new Error('image has zero natural width'));
            }
          }, { once: true });

          element.addEventListener('error', () => {
            clearTimeout(timer);
            reject(new Error('image load error'));
          }, { once: true });
        });
      });
    } catch {
      // Record a useful identifier instead of failing without context.
      const source = await image.evaluate(element =>
        element.currentSrc ||
        element.src ||
        element.alt ||
        '<unknown image>'
      );

      brokenImages.push(source);
    }
  }

  // Return every genuinely broken image to the assertion.
  return brokenImages;
}

// Run the same essential page checks in both configured Chromium profiles.
for (const pageCase of [...primaryPages, errorPage]) {
  test(`${pageCase.name} opens correctly`, async ({ page }) => {
    // Start monitoring before the first byte of the page is requested.
    const runtime = watchPage(page);

    // Open the actual public staging URL.
    const response = await page.goto(pageCase.path, {
      waitUntil: 'domcontentloaded',
    });

    // A navigation without an HTTP response is always invalid for this site.
    expect(response).not.toBeNull();

    // Main pages must be 200 and the dedicated missing page must remain a real 404.
    expect(response.status()).toBe(pageCase.status);

    // Staging must always remain protected outside dist by its IIS header.
    const robotsHeader = response.headers()['x-robots-tag'] || '';
    expect(robotsHeader.toLowerCase()).toContain('noindex');
    expect(robotsHeader.toLowerCase()).toContain('nofollow');
    expect(robotsHeader.toLowerCase()).toContain('noarchive');

    // Give synchronous page scripts and immediately visible media a short settling window.
    await page.waitForTimeout(750);

    // Every rendered page must have a nonempty browser title.
    const title = (await page.title()).trim();
    expect(title.length).toBeGreaterThan(0);

    // Main production pages must never contain a production meta noindex.
    // The custom 404 page is deliberately excluded because noindex is correct there.
    if (pageCase.status === 200) {
      const robotsMeta = await page
        .locator('meta[name="robots"]')
        .allTextContents();

      const robotsMetaContent = await page
        .locator('meta[name="robots"]')
        .evaluateAll(elements =>
          elements.map(element => element.getAttribute('content') || '')
        );

      expect(
        [...robotsMeta, ...robotsMetaContent]
          .join(' ')
          .toLowerCase()
      ).not.toContain('noindex');
    }

    // The common navigation must be mounted by assets/main.js.
    await expect(page.locator('nav[data-navigation]')).toBeAttached();

    // Every expected primary destination must exist in the generated navigation.
    for (const path of navigationPaths) {
      await expect(
        page.locator(`nav[data-navigation] a[href="${path}"]`)
      ).toHaveCount(1);
    }

    // Visible images, such as the logo and current hero/product media,
    // must be actually loaded rather than only present in markup.
    const brokenImages = await findBrokenVisibleImages(page);
    expect(brokenImages, `Broken visible images: ${brokenImages.join(', ')}`).toEqual([]);

    // Fail on uncaught JavaScript exceptions.
    expect(
      runtime.pageErrors,
      `JavaScript errors: ${runtime.pageErrors.join(' | ')}`
    ).toEqual([]);

    // Fail on network-level CSS/JS/image failures.
    expect(
      runtime.failedRequests,
      `Failed critical requests: ${runtime.failedRequests.join(' | ')}`
    ).toEqual([]);

    // Fail on HTTP 4xx/5xx CSS/JS/image responses.
    expect(
      runtime.badResponses,
      `Bad critical responses: ${runtime.badResponses.join(' | ')}`
    ).toEqual([]);
  });
}

// Verify actual navigation interaction instead of merely checking href attributes.
test('primary navigation works', async ({ page }, testInfo) => {
  // Test every main destination from a fresh home-page state.
  for (const path of navigationPaths.filter(path => path !== '/')) {
    // Open the home page before each navigation attempt.
    await page.goto('/', {
      waitUntil: 'domcontentloaded',
    });

    // On the mobile project the navigation is intentionally hidden
    // until the menu button is pressed.
    if (testInfo.project.name === 'mobile-chromium') {
      await page.locator('[data-menu-toggle]').click();
      await expect(page.locator('nav[data-navigation]')).toHaveClass(/is-open/);
    }

    // Click the actual navigation link generated by the site JavaScript.
    await page.locator(`nav[data-navigation] a[href="${path}"]`).click();

    // Confirm that the browser really reached the requested route.
    await expect(page).toHaveURL(new RegExp(`${path.replaceAll('/', '\\/')}$`));
  }
});

test('contact dialog stays inside mobile viewport', async ({ page }, testInfo) => {
  test.skip(
    testInfo.project.name !== 'mobile-chromium',
    'This check belongs to the mobile layout.'
  );

  await page.goto('/', {
    waitUntil: 'domcontentloaded',
  });

  await page.locator('[data-menu-toggle]').click();
  await expect(page.locator('nav[data-navigation]')).toHaveClass(/is-open/);

  await page.locator('.nav__contact').click();

  const dialog = page.locator('[data-contact-dialog]');
  const shell = page.locator('.contact-dialog__shell');
  const firstInput = page.locator('.contact-dialog input').first();

  await expect(dialog).toBeVisible();
  await expect(dialog).toHaveClass(/is-open/);
  await expect(shell).toBeVisible();

  // Wait for the mobile fade transition to reach its final state.
  await page.waitForTimeout(550);

  const readState = () => page.evaluate(() => {
    const dialogElement = document.querySelector('[data-contact-dialog]');
    const shellElement = document.querySelector('.contact-dialog__shell');
    const inputElement = document.querySelector('.contact-dialog input');

    const dialogRect = dialogElement.getBoundingClientRect();
    const shellRect = shellElement.getBoundingClientRect();
    const dialogStyle = getComputedStyle(dialogElement);
    const shellStyle = getComputedStyle(shellElement);

    return {
      viewportWidth: window.innerWidth,
      viewportHeight: window.innerHeight,

      dialog: {
        left: dialogRect.left,
        top: dialogRect.top,
        right: dialogRect.right,
        bottom: dialogRect.bottom,
      },

      shell: {
        left: shellRect.left,
        top: shellRect.top,
        right: shellRect.right,
      },

      rootOverflow: getComputedStyle(document.documentElement).overflow,
      dialogOverflowY: dialogStyle.overflowY,
      shellTransform: shellStyle.transform,
      inputFontSize: Number.parseFloat(
        getComputedStyle(inputElement).fontSize
      ),
    };
  });

  const beforeFocus = await readState();
  const tolerance = 1;

  expect(beforeFocus.dialog.left).toBeGreaterThanOrEqual(-tolerance);
  expect(beforeFocus.dialog.top).toBeGreaterThanOrEqual(-tolerance);
  expect(beforeFocus.dialog.right).toBeLessThanOrEqual(
    beforeFocus.viewportWidth + tolerance
  );
  expect(beforeFocus.dialog.bottom).toBeLessThanOrEqual(
    beforeFocus.viewportHeight + tolerance
  );

  expect(beforeFocus.shell.left).toBeGreaterThanOrEqual(
    beforeFocus.dialog.left - tolerance
  );
  expect(beforeFocus.shell.right).toBeLessThanOrEqual(
    beforeFocus.dialog.right + tolerance
  );

  // Native modal geometry must not depend on a custom root scroll lock.
  expect(beforeFocus.rootOverflow).not.toBe('hidden');

  // The dialog itself owns vertical scrolling.
  expect(beforeFocus.dialogOverflowY).toBe('auto');

  // Mobile Safari must not receive the translated panel animation.
  expect(beforeFocus.shellTransform).toBe('none');

  // iOS Safari must not auto-zoom focused form controls.
  expect(beforeFocus.inputFontSize).toBeGreaterThanOrEqual(16);

  // Focusing a real form field must not move the visible dialog out of bounds.
  await firstInput.click();
  await page.waitForTimeout(150);

  const afterFocus = await readState();

  expect(afterFocus.dialog.left).toBeGreaterThanOrEqual(-tolerance);
  expect(afterFocus.dialog.top).toBeGreaterThanOrEqual(-tolerance);
  expect(afterFocus.dialog.right).toBeLessThanOrEqual(
    afterFocus.viewportWidth + tolerance
  );
  expect(afterFocus.dialog.bottom).toBeLessThanOrEqual(
    afterFocus.viewportHeight + tolerance
  );
});
